name: Test Now
favicon: null
layout_spectrum: 0.99186
typography_spectrum: 0.57582
title: Test Now
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d0d5d8'
    - '#601907'
    - '#8e755d'
    - '#e2402c'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
