name: Test Now
favicon: null
layout_spectrum: 0.99186
typography_spectrum: 0.57582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#effafe'
    - '#000000'
    - '#b93019'
    - '#e1b979'
    - '#497644'
  brandStrength: 0.5
  lightness: 0.5698636737652123
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
